"""added alert model

Revision ID: 07e9f24308ce
Revises: 
Create Date: 2022-07-04 22:31:31.548617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07e9f24308ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_ts', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_ts', sa.TIMESTAMP(), nullable=True),
    sa.Column('temperature_below_threshold_celsius', sa.Integer(), nullable=True),
    sa.Column('alert_destination', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_model')
    # ### end Alembic commands ###
