"""added threshold field

Revision ID: 701eb5429f61
Revises: 07e9f24308ce
Create Date: 2022-07-04 23:58:50.203612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '701eb5429f61'
down_revision = '07e9f24308ce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alert_model', sa.Column('threshold_exceeded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert_model', 'threshold_exceeded')
    # ### end Alembic commands ###
